### ISSUE TITLE
Maven build fails with one Java scoping error - code looks correct...

### ISSUE THREAD

**Issue by twogunredux** [info-sharing-environment/NIEM-Modeling-Tool#3]
(Maven build output) 1 error –“ 
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: ...
plugin:0.19.0:compile (default-compile) on project org.search.niem.uml.papyrus.views.properties: Compilation failure: Compilation failure:
[ERROR] C:\NIEM\NIEM_UML\NIEM-Modeling-Tool-master\NIEM-Modeling-Tool-master\plugins\org.search.niem.uml.papyrus.views.properties\src\main\java\org\search\niem\uml\papyrus\views\properties\xwt\NIEMXwtTabDescriptorProvider.java:[110]
[ERROR] final Set<View> views = ConfigurationManager.instance.constraintEngine.getViews(selection);
[ERROR] ^^^^^^^^
[ERROR] The field ConfigurationManager.instance is not visible
[ERROR] 1 problem (1 error)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.19.0:compile (default-compile) on project org.search.niem.uml.papyrus.views.properties: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: copied.org.apache.maven.plugin.CompilationFailureException: Compilation failure
    at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:441)
    at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute(AbstractOsgiCompilerMojo.java:237)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.search.niem.uml.papyrus.views.properties

 however:
http://git.eclipse.org/c/papyrus/org.eclipse.papyrus.git/tree/plugins/views/properties/org.eclipse.papyrus.views.properties/src/org/eclipse/papyrus/views/properties/runtime/ConfigurationManager.java?id=bbfe5c3b554d6c8212417fa956aa247a0d30d0d6

You can see that the (line 113) that instance is public (static)…Any ideas? This should compile...

**Comment by timezra** [comment]
Thanks for leaving the comment. I am not seeing this locally, so I am guessing that we are using different minor versions of Papyrus (the latest product release was done from 0.10.1, and there has been a more recent release since then - 0.10.2 in February). I have been hoping to hold off on Papyrus-related changes/upgrades until after 1.0.0 is released, but it looks like I might need to find a solution before that.
Could you confirm whether you are currently running Papyrus 0.10.2?
I will try to take a look at it this week.
Thanks again for the report,
---Tim---

**Comment by timezra** [comment]
If you are just looking to evaluate or use the product itself and are not necessarily trying to build the product, I have cut a new release on the Releases page for the product - you should find standalone distributions and a p2 repository there for the plugins/features. Since this might be an issue with the latest version of Papyrus, I would recommend trying out a standalone distribution.
Let me know if this helps.
Regards,
---Tim---

**Comment by twogunredux** [comment]
Tim, not sure what you mean by “currently running Papyrus”…I simply tried to Maven-build the source per the README.md …does this build have a dependency on locally-installed  Papyrus libraries>

FWIW, Kepler is using…Papyrus 0.10.0.v201305291335

**Comment by twogunredux** [comment]
Thank you…

**Comment by timezra** [comment]
Thanks for the reply and for checking on the Papyrus version.
Everything should be downloaded automatically from the repositories configured in the poms and from maven central, so there are no dependencies on anything being installed locally.
I will trying wiping my local maven cache and re-building locally from my machine to see if I can reproduce the problem.
---Tim---

**Comment by twogunredux** [comment]
Tim, not sure what you mean by “currently running Papyrus”…I simply tried to Maven-build the source per the README.md…does this build have a dependency on locally-installed  Papyrus libraries>

FWIW, Kepler is using…Papyrus 0.10.0.v201305291335

**Comment by timezra** [comment]
It appears that between versions 0.10.1 and 0.10.2 of Papyrus a couple of public fields that we were referencing were encapsulated. I have upgraded the version dependencies to use 0.10.2 specifically along with references to the new public methods.
Thanks for pointing this out!
