### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by markbrule** [info-sharing-environment/NIEM-Modeling-Tool#6]
I'm trying to build the tools for Eclipse, and I'm getting an error from the "mvn clean verify" step. It looks like it can't find Epsilon EMF:

[INFO] Resolving dependencies of MavenProject: org.search:org.search.niem.update-site:1.0.0-SNAPSHOT @ C:\Users\mbrule.CORP\NIEM-UML\NIEM-Modeling-Tool\update-site\pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.ws=win32, osgi.os=win32, osgi.arch=x86, org.eclipse.update.install.features=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
[ERROR]   Missing requirement: org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT requires 'org.eclipse.epsilon.evl.emf.validation.feature.feature.group [1.1.0
.201309101707]' but it could not be found
[ERROR]
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.eclipse.jdt.core 3.9.0.v_OTDT_r220_201306071800 to o
rg.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.9.1.v_OTDT_r221_201309101918 to org.eclipse.objectteams.otdt.core.patch.fe
ature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.9.2.v_OTDT_r222_201402180730 to org.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to sat
isfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.evl.emf.validation.feature.feature.group [1.1.0.201309101707].;
Unable to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.feature.feature.group [1.1.0.201309101707].; U
nable to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.emf.feature.feature.group [1.1.0.201309101707].; Una
ble to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.dependencies.feature.feature.group [1.1.0.2013091
01707].; Unable to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.dt.feature.feature.group [1.1.0.20130
9101707].; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.eclipse.jdt.core 3.
9.0.v_OTDT_r220_201306071800 to org.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.9.1.v_OTDT_r221_201309101918 to org.eclip
se.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.9.2.v_OTDT_r222_201402180730 to org.eclipse.objectteams.otdt.core.patch.feature.gr
oup [2.0.0,3.0.0).; Unable to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.evl.emf.validation.feature.feat
ure.group [1.1.0.201309101707].; Unable to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.feature.featu
re.group [1.1.0.201309101707].; Unable to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.emf.feature.feature
.group [1.1.0.201309101707].; Unable to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.dependencies.fea
ture.feature.group [1.1.0.201309101707].; Unable to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.dt.f
eature.feature.group [1.1.0.201309101707].; No solution found because the problem is unsatisfiable.]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:166)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.eclipse.jdt.core 3.9.0.v_OTDT_r220_201306071800 to org.eclipse.ob
jectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.9.1.v_OTDT_r221_201309101918 to org.eclipse.objectteams.otdt.core.patch.feature.group [
2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.9.2.v_OTDT_r222_201402180730 to org.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependen
cy from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.evl.emf.validation.feature.feature.group [1.1.0.201309101707].; Unable to sat
isfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.feature.feature.group [1.1.0.201309101707].; Unable to sati
sfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.emf.feature.feature.group [1.1.0.201309101707].; Unable to satisf
y dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.dependencies.feature.feature.group [1.1.0.201309101707].; Unab
le to satisfy dependency from org.search.niem.update-site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT to org.eclipse.epsilon.core.dt.feature.feature.group [1.1.0.201309101707].; No
 solution found because the problem is unsatisfiable.]
        at org.eclipse.tycho.p2.resolver.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
        at org.eclipse.tycho.p2.resolver.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
        at org.eclipse.tycho.p2.resolver.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
        at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:157)
        at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:107)
        at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.doResolveDependencies(P2TargetPlatformResolver.java:348)
        at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.resolveDependencies(P2TargetPlatformResolver.java:321)
        at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.resolveProject(DefaultTychoDependencyResolver.java:109)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:310)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)

**Comment by dlacy27** [comment]
Hi Mark:
   Are you trying to install the NIEM UML Workbench for Windows? If so, the download has all the Eclipse/Papyrus components needed & you shouldn't need to install anything, other than to insure you have Java 7.02 or higher. If you are installing for MAC OS, we are researching open issues. Let's touch base in the morning...Diane   dlacy@search.org
